### ISSUE TITLE
Including into package.json `dependencies` hash causes error

### ISSUE THREAD

**Issue by alexdiliberto** [open-tux/ember-bulma#33]
Including into my addon's `package.json` `dependencies` object causes the following error. `devDependencies` works as expected. 

Investigation needed

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at CoreObject.module.exports.filterComponents (/Users/<userName>/Repos/<repoName>/node_modules/ember-bulma/index.js:74:18)
    at CoreObject.module.exports.treeForAddon (/Users/<userName>/Repos/<repoName>/node_modules/ember-bulma/index.js:65:17)
    at CoreObject.superWrapper (/Users/<userName>/Repos/<repoName>/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject._treeFor (/Users/<userName>/Repos/<repoName>/node_modules/ember-cli/lib/models/addon.js:341:33)
    at CoreObject.treeFor (/Users/<userName>/Repos/<repoName>/node_modules/ember-cli/lib/models/addon.js:309:21)
    at /Users/<userName>/Repos/<repoName>/node_modules/ember-cli/lib/models/addon.js:242:34
    at Array.map (native)
    at CoreObject.eachAddonInvoke (/Users/<userName>/Repos/<repoName>/node_modules/ember-cli/lib/models/addon.js:240:24)
    at CoreObject.treeFor (/Users/<userName>/Repos/<repoName>/node_modules/ember-cli/lib/models/addon.js:308:22)
    at /Users/<userName>/Repos/<repoName>/node_modules/ember-cli/lib/broccoli/ember-app.js:465:20
```

**Comment by crodriguez1a** [comment]
@alexdiliberto Assume closed by #42 

cc/ @jbailey4
